#!/usr/bin/env python
import urllib3
import random
import string
import jwt  
import time
import requests
import hashlib
import random
import json
import sys
from concurrent.futures import ThreadPoolExecutor
from argparse import ArgumentParser
from colorama import Fore, init

banner = """
░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░░▒▓██████▓▒░░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓████████▓▒░▒▓██████▓▒░ ░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░░▒▓██████▓▒░  
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░      ░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░░▒▓█▓▒░▒▓████████▓▒░▒▓█▓▒░░▒▓█▓▒░▒▓███████▓▒░░▒▓█▓▒░░▒▓█▓▒░                                                
                                                

"""

# Initialize colorama
init(autoreset=True)

# Disable SSL warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def headers_organizer(ip):
    headers =  {
    "ACCEPT": "*/*",
    "ACCEPT-APPLICATION": "*/*",
    "ACCEPT-CHARSET": "*/*",
    "ACCEPTED": "*/*",
    "ACCEPT-ENCODING": "gzip, deflate",
    "ACCEPT-ENCODXNG": "*/*",
    "ACCEPT-LANGUAGE": "en-US,en;q=0.9",
    "ACCEPT-RANGES": "bytes=0-1024",
    "ACCEPT-VERSION": "*/*",
    "ACCESS-CONTROL-ALLOW-CREDENTIALS": random_string(),
    "ACCESS-CONTROL-ALLOW-HEADERS": random_string(),
    "ACCESS-CONTROL-ALLOW-METHODS": random_string(),
    "ACCESS-CONTROL-ALLOW-ORIGIN": "https://" + ip,
    "ACCESS-CONTROL-EXPOSE-HEADERS": random_string(),
    "ACCESS-CONTROL-MAX-AGE": random_string(),
    "ACCESS-CONTROL-REQUEST-HEADERS": random_string(),
    "ACCESS-CONTROL-REQUEST-METHOD": random_string(),
    "ACCESSKEY": random_string(),
    "ACCESS-TOKEN": random_string(),
    "ACTION": random_string(),
    "ADMIN": random_string(),
    "AGE": random_string(),
    "AJAX": random_string(),
    "AKAMAI-ORIGIN-HOP": "https://" + ip,
    "ALLOW": random_string(),
    "APP": random_string(),
    "APPCOOKIE": "sessionid=xyz123",
    "APP-ENV": random_string(),
    "APP-KEY": random_string(),
    "APPLY-TO-REDIRECT-REF": random_string(),
    "APPNAME": random_string(),
    "APPVERSION": random_string(),
    "ATCEPT-LANGUAGE": "en-US,en;q=0.9",
    "AUTH": f"Bearer {generate_random_jwt()}",
    "AUTH-ANY": f"Bearer {generate_random_jwt()}",
    "AUTH-BASIC": f"Bearer {generate_random_jwt()}",
    "AUTH-DIGEST": f"Bearer {generate_random_jwt()}",
    "AUTH-DIGEST-IE": f"Bearer {generate_random_jwt()}",
    "AUTHENTICATION": f"Bearer {generate_random_jwt()}",
    "AUTH-GSSNEG": f"Bearer {generate_random_jwt()}",
    "AUTH-KEY": f"Bearer {generate_random_jwt()}",
    "AUTH-NTLM": f"Bearer {generate_random_jwt()}",
    "AUTHORIZATION": f"Bearer {generate_random_jwt()}",
    "AUTH-PASSWORD": f"Bearer {generate_random_jwt()}",
    "AUTH-REALM": f"Bearer {generate_random_jwt()}",
    "AUTH-TYPE": f"Bearer {generate_random_jwt()}",
    "AUTH-USER": f"Bearer {generate_random_jwt()}",
    "BAD-GATEWAY": random_string(),
    "BAD-REQUEST": random_string(),
    "BAE-ENV-ADDR-BCMS": ip,
    "BAE-ENV-ADDR-BCS": ip,
    "BAE-ENV-ADDR-BUS": ip,
    "BAE-ENV-ADDR-CHANNEL": ip,
    "BAE-ENV-ADDR-SQL-IP": ip,
    "BAE-ENV-ADDR-SQL-PORT": ip,
    "BAE-ENV-AK": random_string(),
    "BAE-ENV-APPID": random_string(),
    "BAE-ENV-SK": random_string(),
    "BAE-LOGID": random_string(),
    "BAR": random_string(),
    "BASE": random_string(),
    "BASE-URL": "https://" + ip,
    "BASIC": random_string(),
    "BEARER-INDICATION": random_string(),
    "BODY-MAXLENGTH": random_string(),
    "BODY-TRUNCATED": random_string(),
    "BRIEF": random_string(),
    "BROWSER-USER-AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "CACHE-CONTROL": "no-cache",
    "CACHE-INFO": random_string(),
    "CASE-FILES": random_string(),
    "CATALOG": random_string(),
    "CATALOG-SERVER": "nginx",
    "CATEGORY": random_string(),
    "CERT-COOKIE": "sessionid=xyz123",
    "CERT-FLAGS": random_string(),
    "CERT-ISSUER": random_string(),
    "CERT-KEYSIZE": random_string(),
    "CERT-SECRETKEYSIZE": random_string(),
    "CERT-SERIALNUMBER": random_string(),
    "CERT-SERVER-ISSUER": "nginx",
    "CERT-SERVER-SUBJECT": "nginx",
    "CERT-SUBJECT": random_string(),
    "CF-CONNECTING-IP": ip,
    "CF-IPCOUNTRY": ip,
    "CF-TEMPLATE-PATH": random_string(),
    "CF-VISITOR": random_string(),
    "CH": random_string(),
    "CHALLENGE-RESPONSE": random_string(),
    "CHARSET": random_string(),
    "CHUNK-SIZE": random_string(),
    "CLIENT": random_string(),
    "CLIENT-ADDRESS": ip,
    "CLIENTADDRESS": ip,
    "CLIENT-BAD-REQUEST": random_string(),
    "CLIENT-CONFLICT": random_string(),
    "CLIENT-ERROR-CANNOT-ACCESS-LOCAL-FILE": random_string(),
    "CLIENT-ERROR-CANNOT-CONNECT": random_string(),
    "CLIENT-ERROR-COMMUNICATION-FAILURE": random_string(),
    "CLIENT-ERROR-CONNECT": random_string(),
    "CLIENT-ERROR-INVALID-PARAMETERS": random_string(),
    "CLIENT-ERROR-INVALID-SERVER-ADDRESS": ip,
    "CLIENT-ERROR-NO-ERROR": random_string(),
    "CLIENT-ERROR-PROTOCOL-FAILURE": random_string(),
    "CLIENT-ERROR-UNSPECIFIED-ERROR": random_string(),
    "CLIENT-EXPECTATION-FAILED": random_string(),
    "CLIENT-FORBIDDEN": random_string(),
    "CLIENT-GONE": random_string(),
    "CLIENT-IP": ip,
    "CLIENTIP": ip,
    "CLIENT-LENGTH-REQUIRED": random_string(),
    "CLIENT-METHOD-NOT-ALLOWED": random_string(),
    "CLIENT-NOT-ACCEPTABLE": "*/*",
    "CLIENT-NOT-FOUND": random_string(),
    "CLIENT-PAYMENT-REQUIRED": random_string(),
    "CLIENT-PRECONDITION-FAILED": random_string(),
    "CLIENT-PROXY-AUTH-REQUIRED": f"Bearer {generate_random_jwt()}",
    "CLIENT-QUIRK-MODE": random_string(),
    "CLIENT-REQUESTED-RANGE-NOT-POSSIBLE": "bytes=0-1024",
    "CLIENT-REQUEST-TIMEOUT": random_string(),
    "CLIENT-REQUEST-TOO-LARGE": random_string(),
    "CLIENT-REQUEST-URI-TOO-LARGE": random_string(),
    "CLIENT-UNAUTHORIZED": f"Bearer {generate_random_jwt()}",
    "CLIENT-UNSUPPORTED-MEDIA-TYPE": random_string(),
    "CLOUDFRONT-VIEWER-COUNTRY": random_string(),
    "CLOUDINARY-NAME": random_string(),
    "CLOUDINARY-PUBLIC-ID": random_string(),
    "CLOUDINARYURL": "https://" + ip,
    "CLOUDINARY-VERSION": random_string(),
    "CODE": random_string(),
    "COMING-FROM": random_string(),
    "COMPRESS": random_string(),
    "CONFLICT": random_string(),
    "CONNECTION": "keep-alive",
    "CONNECTION-TYPE": "keep-alive",
    "CONTACT": random_string(),
    "CONTENT": random_string(),
    "CONTENT-DISPOSITION": random_string(),
    "CONTENT-ENCODING": "gzip, deflate",
    "CONTENT-LANGUAGE": "en-US,en;q=0.9",
    "CONTENT-LENGTH": random_string(),
    "CONTENT-LOCATION": random_string(),
    "CONTENT-MD5": random_string(),
    "CONTENT-RANGE": "bytes=0-1024",
    "CONTENT-SECURITY-POLICY": random_string(),
    "CONTENT-SECURITY-POLICY-REPORT-ONLY": random_string(),
    "CONTENT-TYPE": "application/json",
    "CONTENT-TYPE-XHTML": "application/json",
    "CONTEXT-PATH": random_string(),
    "CONTINUE": random_string(),
    "COOKIE": "sessionid=xyz123",
    "COOKIE2": "sessionid=xyz123",
    "COOKIE-DOMAIN": "sessionid=xyz123",
    "COOKIE-HTTPONLY": "sessionid=xyz123",
    "COOKIE-PARSE-RAW": "sessionid=xyz123",
    "COOKIE-PATH": "sessionid=xyz123",
    "COOKIES": "sessionid=xyz123",
    "COOKIE-SECURE": "sessionid=xyz123",
    "COOKIE-VARS": "sessionid=xyz123",
    "CORE-BASE": random_string(),
    "CREATED": random_string(),
    "CREDENTIALS-FILEPATH": random_string(),
    "CURL": "https://" + ip,
    "CURL-MULTITHREADED": "https://" + ip,
    "CUSTOM-HEADER": random_string(),
    "CUSTOM-SECRET-HEADER": random_string(),
    "DATASERVICEVERSION": random_string(),
    "DATE": "Mon, 10 Mar 2025 12:00:00 GMT",
    "DEBUG": random_string(),
    "DEFLATE-LEVEL-DEF": random_string(),
    "DEFLATE-LEVEL-MAX": random_string(),
    "DEFLATE-LEVEL-MIN": random_string(),
    "DEFLATE-STRATEGY-DEF": random_string(),
    "DEFLATE-STRATEGY-FILT": random_string(),
    "DEFLATE-STRATEGY-FIXED": random_string(),
    "DEFLATE-STRATEGY-HUFF": random_string(),
    "DEFLATE-STRATEGY-RLE": random_string(),
    "DEFLATE-TYPE-GZIP": ip,
    "DEFLATE-TYPE-RAW": random_string(),
    "DEFLATE-TYPE-ZLIB": random_string(),
    "DELETE": random_string(),
    "DEPTH": random_string(),
    "DESTINATION": random_string(),
    "DESTROY": random_string(),
    "DEVBLOCKSPROXYBASE": ip,
    "DEVBLOCKSPROXYHOST": ip,
    "DEVBLOCKSPROXYSSL": ip,
    "DEVICE-STOCK-UA": random_string(),
    "DIGEST": random_string(),
    "DIR": random_string(),
    "DIR-NAME": random_string(),
    "DIR-RESOURCE": random_string(),
    "DISABLE-GZIP": ip,
    "DKIM-SIGNATURE": random_string(),
    "DNT": random_string(),
    "DOWNLOAD-ATTACHMENT": random_string(),
    "DOWNLOAD-BAD-URL": "https://" + ip,
    "DOWNLOAD-BZ2": random_string(),
    "DOWNLOAD-CUT-SHORT": random_string(),
    "DOWNLOAD-E-HEADERS-SENT": random_string(),
    "DOWNLOAD-E-INVALID-ARCHIVE-TYPE": random_string(),
    "DOWNLOAD-E-INVALID-CONTENT-TYPE": "application/json",
    "DOWNLOAD-E-INVALID-FILE": random_string(),
    "DOWNLOAD-E-INVALID-PARAM": random_string(),
    "DOWNLOAD-E-INVALID-REQUEST": random_string(),
    "DOWNLOAD-E-INVALID-RESOURCE": random_string(),
    "DOWNLOAD-E-NO-EXT-MMAGIC": random_string(),
    "DOWNLOAD-E-NO-EXT-ZLIB": random_string(),
    "DOWNLOAD-INLINE": random_string(),
    "DOWNLOAD-MIME-TYPE": random_string(),
    "DOWNLOAD-NO-SERVER": "nginx",
    "DOWNLOAD-SIZE": random_string(),
    "DOWNLOAD-STATUS-NOT-FOUND": random_string(),
    "DOWNLOAD-STATUS-SERVER-ERROR": "nginx",
    "DOWNLOAD-STATUS-UNAUTHORIZED": f"Bearer {generate_random_jwt()}",
    "DOWNLOAD-STATUS-UNKNOWN": random_string(),
    "DOWNLOAD-TAR": random_string(),
    "DOWNLOAD-TGZ": random_string(),
    "DOWNLOAD-URL": "https://" + ip,
    "DOWNLOAD-ZIP": ip,
    "E-ENCODING": "gzip, deflate",
    "E-HEADER": random_string(),
    "E-INVALID-PARAM": random_string(),
    "E-MALFORMED-HEADERS": random_string(),
    "E-MESSAGE-TYPE": random_string(),
    "ENABLE-GZIP": ip,
    "ENABLE-NO-CACHE-HEADERS": random_string(),
    "ENCODING-STREAM-FLUSH-FULL": "gzip, deflate",
    "ENCODING-STREAM-FLUSH-NONE": "gzip, deflate",
    "ENCODING-STREAM-FLUSH-SYNC": "gzip, deflate",
    "ENV-SILLA-ENVIRONMENT": random_string(),
    "ENV-VARS": random_string(),
    "E-QUERYSTRING": random_string(),
    "E-REQUEST": random_string(),
    "E-REQUEST-METHOD": random_string(),
    "E-REQUEST-POOL": random_string(),
    "E-RESPONSE": random_string(),
    "ERROR": random_string(),
    "ERROR-1": random_string(),
    "ERROR-2": random_string(),
    "ERROR-3": random_string(),
    "ERROR-4": random_string(),
    "ERROR-FORMATTING-HTML": random_string(),
    "E-RUNTIME": random_string(),
    "E-SOCKET": random_string(),
    "ESPO-AUTHORIZATION": f"Bearer {generate_random_jwt()}",
    "ESPO-CGI-AUTH": f"Bearer {generate_random_jwt()}",
    "ETAG": "W/\"123456\"",
    "E-URL": "https://" + ip,
    "EVE-CHARID": random_string(),
    "EVE-CHARNAME": random_string(),
    "EVE-SOLARSYSTEMID": random_string(),
    "EVE-SOLARSYSTEMNAME": random_string(),
    "EVE-TRUSTED": random_string(),
    "EX-COPY-MOVIE": random_string(),
    "EXPECT": random_string(),
    "EXPECTATION-FAILED": random_string(),
    "EXPIRES": "0",
    "EXT": random_string(),
    "FAILED-DEPENDENCY": random_string(),
    "FAKE-HEADER": random_string(),
    "FASTLY-CLIENT-IP": ip,
    "FB-APPID": random_string(),
    "FB-SECRET": random_string(),
    "FILENAME": random_string(),
    "FILE-NOT-FOUND": random_string(),
    "FILES": random_string(),
    "FILES-VARS": random_string(),
    "FIRE-BREATHING-DRAGON": random_string(),
    "FOO": random_string(),
    "FOO-BAR": random_string(),
    "FORBIDDEN": random_string(),
    "FORCE-LANGUAGE": "en-US,en;q=0.9",
    "FORCE-LOCAL-XHPROF": random_string(),
    "FORMAT": random_string(),
    "FORWARDED": random_string(),
    "FORWARDED-FOR": random_string(),
    "FORWARDED-FOR-IP": ip,
    "FORWARDED-PROTO": random_string(),
    "FROM": random_string(),
    "FROMLINK": random_string(),
    "FRONT-END-HTTPS": random_string(),
    "GATEWAY-INTERFACE": random_string(),
    "GATEWAY-TIME-OUT": random_string(),
    "GET": random_string(),
    "GET-VARS": random_string(),
    "GIVENNAME": random_string(),
    "GLOBAL-ALL": random_string(),
    "GLOBAL-COOKIE": "sessionid=xyz123",
    "GLOBAL-GET": random_string(),
    "GLOBAL-POST": random_string(),
    "GONE": random_string(),
    "GOOGLE-CODE-PROJECT-HOSTING-HOOK-HMAC": ip,
    "GZIP-LEVEL": ip,
    "H0ST": random_string(),
    "HEAD": random_string(),
    "HEADER": random_string(),
    "HEADER-LF": random_string(),
    "HEADER-STATUS-CLIENT-ERROR": random_string(),
    "HEADER-STATUS-INFORMATIONAL": random_string(),
    "HEADER-STATUS-REDIRECT": random_string(),
    "HEADER-STATUS-SERVER-ERROR": "nginx",
    "HEADER-STATUS-SUCCESSFUL": random_string(),
    "HOME": random_string(),
    "HOST": ip,
    "HOSTI": ip,
    "HOST-LIVESERVER": ip,
    "HOST-NAME": ip,
    "HOST-UNAVAILABLE": ip,
    "HTACCESS": random_string(),
    "HTTP-ACCEPT": "*/*",
    "HTTP-ACCEPT-ENCODING": "gzip, deflate",
    "HTTP-ACCEPT-LANGUAGE": "en-US,en;q=0.9",
    "HTTP-AUTHORIZATION": f"Bearer {generate_random_jwt()}",
    "HTTP-CONNECTION": "keep-alive",
    "HTTP-COOKIE": "sessionid=xyz123",
    "HTTP-HOST": ip,
    "HTTP-PHONE-NUMBER": random_string(),
    "HTTP-REFERER": "https://" + ip,
    "HTTPS": random_string(),
    "HTTPS-FROM-LB": random_string(),
    "HTTPS-KEYSIZE": random_string(),
    "HTTPS-SECRETKEYSIZE": random_string(),
    "HTTPS-SERVER-ISSUER": "nginx",
    "HTTPS-SERVER-SUBJECT": "nginx",
    "HTTP-URL": "https://" + ip,
    "HTTP-USER-AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "IF": random_string(),
    "IF-MATCH": random_string(),
    "IF-MODIFIED-SINCE": random_string(),
    "IF-MODIFIED-SINCE-VERSION": random_string(),
    "IF-NONE-MATCH": random_string(),
    "IF-POSTED-BEFORE": random_string(),
    "IF-RANGE": "bytes=0-1024",
    "IF-UNMODIFIED-SINCE": random_string(),
    "IF-UNMODIFIED-SINCE-VERSION": random_string(),
    "IMAGE": random_string(),
    "IMAGES": random_string(),
    "INCAP-CLIENT-IP": ip,
    "INFO": random_string(),
    "INFO-DOWNLOAD-SIZE": random_string(),
    "INFO-DOWNLOAD-TIME": random_string(),
    "INFO-RETURN-CODE": random_string(),
    "INFO-TOTAL-REQUEST-STAT": random_string(),
    "INFO-TOTAL-RESPONSE-STAT": random_string(),
    "INSUFFICIENT-STORAGE": random_string(),
    "INTERNAL-SERVER-ERROR": "nginx",
    "IPRESOLVE-ANY": ip,
    "IPRESOLVE-V4": ip,
    "IPRESOLVE-V6": ip,
    "ISCHEDULE-VERSION": random_string(),
    "IV-GROUPS": random_string(),
    "IV-USER": random_string(),
    "JAVASCRIPT": ip,
    "JENKINS": random_string(),
    "KEEP-ALIVE": random_string(),
    "KISS-RPC": random_string(),
    "LABEL": random_string(),
    "LARGE-ALLOCATION": random_string(),
    "LAST-EVENT-ID": random_string(),
    "LAST-MODIFIED": random_string(),
    "LENGTH-REQUIRED": random_string(),
    "LINK": random_string(),
    "LOCAL-ADDR": ip,
    "LOCAL-CONTENT-SHA1": random_string(),
    "LOCAL-DIR": random_string(),
    "LOCATION": random_string(),
    "LOCKED": random_string(),
    "LOCK-TOKEN": random_string(),
    "MAIL": random_string(),
    "MAX-CONN": random_string(),
    "MAXDATASERVICEVERSION": random_string(),
    "MAX-FORWARDS": random_string(),
    "MAX-REQUEST-SIZE": random_string(),
    "MAX-URI-LENGTH": random_string(),
    "MESSAGE": random_string(),
    "MESSAGE-B": random_string(),
    "METH-": random_string(),
    "METH-ACL": random_string(),
    "METH-BASELINE-CONTROL": random_string(),
    "METH-CHECKIN": random_string(),
    "METH-CHECKOUT": random_string(),
    "METH-CONNECT": random_string(),
    "METH-COPY": random_string(),
    "METH-DELETE": random_string(),
    "METH-GET": random_string(),
    "METH-HEAD": random_string(),
    "METH-LABEL": random_string(),
    "METH-LOCK": random_string(),
    "METH-MERGE": random_string(),
    "METH-MKACTIVITY": random_string(),
    "METH-MKCOL": random_string(),
    "METH-MKWORKSPACE": random_string(),
    "METH-MOVE": random_string(),
    "METHOD": random_string(),
    "METHOD-NOT-ALLOWED": random_string(),
    "METH-OPTIONS": random_string(),
    "METH-POST": random_string(),
    "METH-PROPFIND": random_string(),
    "METH-PROPPATCH": random_string(),
    "METH-PUT": random_string(),
    "METH-REPORT": random_string(),
    "METH-TRACE": random_string(),
    "METH-UNCHECKOUT": random_string(),
    "METH-UNLOCK": random_string(),
    "METH-UPDATE": "Mon, 10 Mar 2025 12:00:00 GMT",
    "METH-VERSION-CONTROL": random_string(),
    "MIMETYPE": random_string(),
    "MODAUTH": f"Bearer {generate_random_jwt()}",
    "MODE": random_string(),
    "MOD-ENV": random_string(),
    "MOD-REWRITE": random_string(),
    "MOD-SECURITY-MESSAGE": random_string(),
    "MODULE-CLASS": random_string(),
    "MODULE-CLASS-PATH": random_string(),
    "MODULE-NAME": random_string(),
    "MOVED-PERMANENTLY": random_string(),
    "MOVED-TEMPORARILY": random_string(),
    "MS-ASPROTOCOLVERSION": random_string(),
    "MSG-NONE": random_string(),
    "MSG-REQUEST": random_string(),
    "MSG-RESPONSE": random_string(),
    "MSISDN": random_string(),
    "MULTIPART-BOUNDARY": ip,
    "MULTIPLE-CHOICES": ip,
    "MULTI-STATUS": random_string(),
    "MY-HEADER": random_string(),
    "MYSQLPORT": random_string(),
    "NATIVE-SOCKETS": random_string(),
    "NEGOTIATE": random_string(),
    "NL": random_string(),
    "NO-CONTENT": random_string(),
    "NON-AUTHORITATIVE": f"Bearer {generate_random_jwt()}",
    "NONCE": random_string(),
    "NOT-ACCEPTABLE": "*/*",
    "NOT-EXISTS": random_string(),
    "NOT-EXTENDED": random_string(),
    "NOT-FOUND": random_string(),
    "NOTIFICATION-TEMPLATE": random_string(),
    "NOT-IMPLEMENTED": random_string(),
    "NOT-MODIFIED": random_string(),
    "OC-CHUNKED": random_string(),
    "OCS-APIREQUEST": random_string(),
    "OK": random_string(),
    "ON-BEHALF-OF": random_string(),
    "ONERROR-CONTINUE": random_string(),
    "ONERROR-DIE": random_string(),
    "ONERROR-RETURN": random_string(),
    "OPENCART": random_string(),
    "OPTIONS": random_string(),
    "ORGANIZER": random_string(),
    "ORIGIN": "https://" + ip,
    "ORIGINATOR": "https://" + ip,
    "ORIG_PATH_INFO": random_string(),
    "OVERWRITE": random_string(),
    "PARAMS-ALLOW-COMMA": random_string(),
    "PARAMS-ALLOW-FAILURE": random_string(),
    "PARAMS-DEFAULT": random_string(),
    "PARAMS-GET-CATID": random_string(),
    "PARAMS-GET-CURRENTDAY": random_string(),
    "PARAMS-GET-DISPOSITION": random_string(),
    "PARAMS-GET-DOWNWARDS": random_string(),
    "PARAMS-GET-GIVENDATE": "Mon, 10 Mar 2025 12:00:00 GMT",
    "PARAMS-GET-LANG": random_string(),
    "PARAMS-GET-TYPE": random_string(),
    "PARAMS-RAISE-ERROR": random_string(),
    "PARTIAL-CONTENT": random_string(),
    "PASSKEY": random_string(),
    "PASSWORD": random_string(),
    "PATH": random_string(),
    "PATH-BASE": random_string(),
    "PATH-INFO": random_string(),
    "PATH-THEMES": random_string(),
    "PATH-TRANSLATED": random_string(),
    "PAYMENT-REQUIRED": random_string(),
    "PC-REMOTE-ADDR": ip,
    "PHONE-NUMBER": random_string(),
    "PHP": random_string(),
    "PHP-AUTH-PW": f"Bearer {generate_random_jwt()}",
    "PHP-AUTH-USER": f"Bearer {generate_random_jwt()}",
    "PHPTHREADS": random_string(),
    "PINK-PONY": random_string(),
    "PORT": random_string(),
    "PORTSENSOR-AUTH": f"Bearer {generate_random_jwt()}",
    "POST": random_string(),
    "POST-ERROR": random_string(),
    "POST-FILES": random_string(),
    "POSTREDIR-301": random_string(),
    "POSTREDIR-302": random_string(),
    "POSTREDIR-ALL": random_string(),
    "POST-VARS": random_string(),
    "PRAGMA": "no-cache",
    "PRAGMA-NO-CACHE": "no-cache",
    "PRECONDITION-FAILED": random_string(),
    "PREFER": random_string(),
    "PROCESSING": random_string(),
    "PROFILE": random_string(),
    "PROTOCOL": random_string(),
    "PROTOCOLS": random_string(),
    "PROXY": ip,
    "PROXY-AGENT": ip,
    "PROXY-AUTHENTICATE": f"Bearer {generate_random_jwt()}",
    "PROXY-AUTHENTICATION-REQUIRED": f"Bearer {generate_random_jwt()}",
    "PROXY-AUTHORIZATION": f"Bearer {generate_random_jwt()}",
    "PROXY-CONNECTION": "keep-alive",
    "PROXY-HOST": ip,
    "PROXY-HTTP": ip,
    "PROXY-HTTP-1-0": ip,
    "PROXY-PASSWORD": ip,
    "PROXY-PORT": ip,
    "PROXY-PWD": ip,
    "PROXY-REQUEST-FULLURI": ip,
    "PROXY-SOCKS4": ip,
    "PROXY-SOCKS4A": ip,
    "PROXY-SOCKS5": ip,
    "PROXY-SOCKS5-HOSTNAME": ip,
    "PROXY-URL": "https://" + ip,
    "PROXY-USER": ip,
    "PUBLIC-KEY-PINS": random_string(),
    "PUBLIC-KEY-PINS-REPORT-ONLY": random_string(),
    "PULL": random_string(),
    "PUT": random_string(),
    "QUERY-STRING": random_string(),
    "QUERYSTRING": random_string(),
    "QUERYSTRING-TYPE-ARRAY": random_string(),
    "QUERYSTRING-TYPE-BOOL": random_string(),
    "QUERYSTRING-TYPE-FLOAT": random_string(),
    "QUERYSTRING-TYPE-INT": random_string(),
    "QUERYSTRING-TYPE-OBJECT": random_string(),
    "QUERYSTRING-TYPE-STRING": random_string(),
    "RANGE": "bytes=0-1024",
    "RANGE-NOT-SATISFIABLE": "bytes=0-1024",
    "RAW-POST-DATA": random_string(),
    "READ-STATE-BEGIN": random_string(),
    "READ-STATE-BODY": random_string(),
    "READ-STATE-HEADERS": random_string(),
    "REAL-IP": ip,
    "REAL-METHOD": random_string(),
    "REASON": random_string(),
    "REASON-PHRASE": random_string(),
    "RECIPIENT": ip,
    "REDIRECT": random_string(),
    "REDIRECTED-ACCEPT-LANGUAGE": "en-US,en;q=0.9",
    "REDIRECT-FOUND": random_string(),
    "REDIRECTION-FOUND": random_string(),
    "REDIRECTION-MULTIPLE-CHOICES": ip,
    "REDIRECTION-NOT-MODIFIED": random_string(),
    "REDIRECTION-PERMANENT": random_string(),
    "REDIRECTION-SEE-OTHER": random_string(),
    "REDIRECTION-TEMPORARY": random_string(),
    "REDIRECTION-UNUSED": random_string(),
    "REDIRECTION-USE-PROXY": ip,
    "REDIRECT-PERM": random_string(),
    "REDIRECT-POST": random_string(),
    "REDIRECT-PROBLEM-WITHOUTWWW": random_string(),
    "REDIRECT-PROBLEM-WITHWWW": random_string(),
    "REDIRECT-PROXY": ip,
    "REDIRECT-TEMP": random_string(),
    "REF": random_string(),
    "REFERER": "https://" + ip,
    "REFERRER": random_string(),
    "REFERRER-POLICY": random_string(),
    "REFFERER": random_string(),
    "REFRESH": random_string(),
    "REMIX-HASH": random_string(),
    "REMOTE-ADDR": ip,
    "REMOTE-HOST": ip,
    "REMOTE-HOST-WP": ip,
    "REMOTE-USER": random_string(),
    "REMOTE-USERHTTPS": random_string(),
    "REPORT-TO": random_string(),
    "REQUEST": random_string(),
    "REQUEST2-TESTS-BASE-URL": "https://" + ip,
    "REQUEST2-TESTS-PROXY-HOST": ip,
    "REQUEST-ENTITY-TOO-LARGE": random_string(),
    "REQUEST-ERROR": random_string(),
    "REQUEST-ERROR-FILE": random_string(),
    "REQUEST-ERROR-GZIP-CRC": ip,
    "REQUEST-ERROR-GZIP-DATA": ip,
    "REQUEST-ERROR-GZIP-METHOD": ip,
    "REQUEST-ERROR-GZIP-READ": ip,
    "REQUEST-ERROR-PROXY": ip,
    "REQUEST-ERROR-REDIRECTS": random_string(),
    "REQUEST-ERROR-RESPONSE": random_string(),
    "REQUEST-ERROR-URL": "https://" + ip,
    "REQUEST-HTTP-VER-1-0": random_string(),
    "REQUEST-HTTP-VER-1-1": random_string(),
    "REQUEST-MBSTRING": random_string(),
    "REQUEST-METHOD": random_string(),
    "REQUEST-METHOD-": random_string(),
    "REQUEST-METHOD-DELETE": random_string(),
    "REQUEST-METHOD-GET": random_string(),
    "REQUEST-METHOD-HEAD": random_string(),
    "REQUEST-METHOD-OPTIONS": random_string(),
    "REQUEST-METHOD-POST": random_string(),
    "REQUEST-METHOD-PUT": random_string(),
    "REQUEST-METHOD-TRACE": random_string(),
    "REQUEST-TIME-OUT": random_string(),
    "REQUEST-TIMEOUT": random_string(),
    "REQUESTTOKEN": random_string(),
    "REQUEST-URI": random_string(),
    "REQUEST-URI-TOO-LARGE": random_string(),
    "REQUEST-VARS": random_string(),
    "RESET-CONTENT": random_string(),
    "RESPONSE": random_string(),
    "REST-KEY": random_string(),
    "REST-SIGN": random_string(),
    "RETRY-AFTER": random_string(),
    "RETURNED-ERROR": random_string(),
    "RLNCLIENTIPADDR": ip,
    "ROOT": random_string(),
    "SAFE-PORTS-LIST": random_string(),
    "SAFE-PORTS-SSL-LIST": random_string(),
    "SCHEDULE-REPLY": random_string(),
    "SCHEME": random_string(),
    "SCRIPT-NAME": ip,
    "SECRETKEY": random_string(),
    "SEC-WEBSOCKET-ACCEPT": "*/*",
    "SEC-WEBSOCKET-EXTENSIONS": random_string(),
    "SEC-WEBSOCKET-KEY": random_string(),
    "SEC-WEBSOCKET-KEY1": random_string(),
    "SEC-WEBSOCKET-KEY2": random_string(),
    "SEC-WEBSOCKET-ORIGIN": "https://" + ip,
    "SEC-WEBSOCKET-PROTOCOL": random_string(),
    "SEC-WEBSOCKET-VERSION": random_string(),
    "SEE-OTHER": random_string(),
    "SELF": random_string(),
    "SEND-X-FRAME-OPTIONS": random_string(),
    "SERVER": "nginx",
    "SERVER-BAD-GATEWAY": "nginx",
    "SERVER-ERROR": "nginx",
    "SERVER-GATEWAY-TIMEOUT": "nginx",
    "SERVER-INTERNAL": "nginx",
    "SERVER-NAME": "nginx",
    "SERVER-NOT-IMPLEMENTED": "nginx",
    "SERVER-PORT": "nginx",
    "SERVER-PORT-SECURE": "nginx",
    "SERVER-PROTOCOL": "nginx",
    "SERVER-SERVICE-UNAVAILABLE": "nginx",
    "SERVER-SOFTWARE": "nginx",
    "SERVER-UNSUPPORTED-VERSION": "nginx",
    "SERVER-VARS": "nginx",
    "SERVER-VARSABANTECART": "nginx",
    "SERVICE-UNAVAILABLE": random_string(),
    "SESSION-ID-TAG": random_string(),
    "SESSION-VARS": random_string(),
    "SET-COOKIE": "sessionid=xyz123",
    "SET-COOKIE2": "sessionid=xyz123",
    "SHIB-": random_string(),
    "SHIB-APPLICATION-ID": random_string(),
    "SHIB-IDENTITY-PROVIDER": random_string(),
    "SHIB-LOGOUTURL": "https://" + ip,
    "SHOPILEX": random_string(),
    "SLUG": random_string(),
    "SN": random_string(),
    "SOAPACTION": random_string(),
    "SOCKET-CONNECTION-ERR": "keep-alive",
    "SOCKETLOG": random_string(),
    "SOMEVAR": random_string(),
    "SOURCEMAP": random_string(),
    "SP-CLIENT": random_string(),
    "SP-HOST": ip,
    "SSL": random_string(),
    "SSL-HTTPS": random_string(),
    "SSL-OFFLOADED": random_string(),
    "SSL-SESSION-ID": random_string(),
    "SSLSESSIONID": random_string(),
    "SSL-VERSION-ANY": random_string(),
    "START": random_string(),
    "STATUS": random_string(),
    "STATUS-": random_string(),
    "STATUS-403": random_string(),
    "STATUS-403-ADMIN-DEL": random_string(),
    "STATUS-404": random_string(),
    "STATUS-BAD-REQUEST": random_string(),
    "STATUS-CODE": random_string(),
    "STATUS-FORBIDDEN": random_string(),
    "STATUS-OK": random_string(),
    "STATUS-PLATFORM-403": random_string(),
    "STRICT-TRANSPORT-SECURITY": random_string(),
    "STR-MATCH": random_string(),
    "SUCCESS-ACCEPTED": "*/*",
    "SUCCESS-CREATED": random_string(),
    "SUCCESS-NO-CONTENT": random_string(),
    "SUCCESS-NON-AUTHORITATIVE": f"Bearer {generate_random_jwt()}",
    "SUCCESS-OK": random_string(),
    "SUCCESS-PARTIAL-CONTENT": random_string(),
    "SUCCESS-RESET-CONTENT": random_string(),
    "SUPPORT": random_string(),
    "SUPPORT-ENCODINGS": "gzip, deflate",
    "SUPPORT-EVENTS": random_string(),
    "SUPPORT-MAGICMIME": random_string(),
    "SUPPORT-REQUESTS": random_string(),
    "SUPPORT-SSLREQUESTS": random_string(),
    "SURROGATE-CAPABILITY": random_string(),
    "SWITCHING-PROTOCOLS": random_string(),
    "TE": random_string(),
    "TEMPORARY-REDIRECT": random_string(),
    "TEST": random_string(),
    "TEST-CONFIG": random_string(),
    "TEST-SERVER-PATH": "nginx",
    "TEST-SOMETHING-ANYTHING": random_string(),
    "TICKET": random_string(),
    "TIME-OUT": random_string(),
    "TIMEOUT": random_string(),
    "TIMING-ALLOW-ORIGIN": "https://" + ip,
    "TITLE": random_string(),
    "TK": random_string(),
    "TMP": random_string(),
    "TOKEN": random_string(),
    "TRAILER": random_string(),
    "TRANSFER-ENCODING": "gzip, deflate",
    "TRANSLATE": random_string(),
    "TRANSPORT-ERR": random_string(),
    "TRUE-CLIENT-IP": ip,
    "UA": random_string(),
    "UA-COLOR": random_string(),
    "UA-CPU": random_string(),
    "UA-OS": random_string(),
    "UA-PIXELS": random_string(),
    "UA-RESOLUTION": random_string(),
    "UA-VOICE": random_string(),
    "UNAUTHORIZED": f"Bearer {generate_random_jwt()}",
    "UNENCODED-URL": "https://" + ip,
    "UNIT-TEST-MODE": random_string(),
    "UNLESS-MODIFIED-SINCE": random_string(),
    "UNPROCESSABLE-ENTITY": random_string(),
    "UNSUPPORTED-MEDIA-TYPE": random_string(),
    "UPGRADE": "websocket",
    "UPGRADE-INSECURE-REQUESTS": "websocket",
    "UPGRADE-REQUIRED": "websocket",
    "UPLOAD-DEFAULT-CHMOD": random_string(),
    "URI": random_string(),
    "URL": "https://" + ip,
    "URL-FROM-ENV": "https://" + ip,
    "URL-JOIN-PATH": "https://" + ip,
    "URL-JOIN-QUERY": "https://" + ip,
    "URL-REPLACE": "https://" + ip,
    "URL-SANITIZE-PATH": "https://" + ip,
    "URL-STRIP-": ip,
    "URL-STRIP-ALL": ip,
    "URL-STRIP-AUTH": ip,
    "URL-STRIP-FRAGMENT": ip,
    "URL-STRIP-PASS": ip,
    "URL-STRIP-PATH": ip,
    "URL-STRIP-PORT": ip,
    "URL-STRIP-QUERY": ip,
    "URL-STRIP-USER": ip,
    "USE-GZIP": ip,
    "USE-PROXY": ip,
    "USER": random_string(),
    "USERAGENT": random_string(),
    "USER-AGENT-VIA": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "USERAGENT-VIA": "1.1 proxy",
    "USER-EMAIL": random_string(),
    "USER-ID": random_string(),
    "USER-MAIL": random_string(),
    "USER-NAME": random_string(),
    "USER-PHOTOS": random_string(),
    "UTIL": random_string(),
    "VARIANT-ALSO-VARIES": random_string(),
    "VARY": random_string(),
    "VERBOSE": random_string(),
    "VERBOSE-THROTTLE": random_string(),
    "VERIFY-CERT": random_string(),
    "VERSION": random_string(),
    "VERSION-1-0": random_string(),
    "VERSION-1-1": random_string(),
    "VERSION-ANY": random_string(),
    "VERSIONCODE": random_string(),
    "VERSION-NONE": random_string(),
    "VERSION-NOT-SUPPORTED": random_string(),
    "VIA": "1.1 proxy",
    "VIAD": "1.1 proxy",
    "WAF-STUFF-BELOW": random_string(),
    "WAP-CONNECTION": "keep-alive",
    "WARNING": "199   + ip\"Warning message\"",
    "WEBODF-MEMBER-ID": random_string(),
    "WEBODF-SESSION-ID": random_string(),
    "WEBODF-SESSION-REVISION": random_string(),
    "WEB-SERVER-API": "nginx",
    "WORK-DIRECTORY": random_string(),
    "WWW-ADDRESS": ip,
    "WWW-AUTHENTICATE": f"Bearer {generate_random_jwt()}",
    "X": random_string(),
    "X-": random_string(),
    "X-AASTRA-EXPMOD1": random_string(),
    "X-AASTRA-EXPMOD2": random_string(),
    "X-AASTRA-EXPMOD3": random_string(),
    "X-ACCEL-MAPPING": random_string(),
    "X-ACCESS-TOKEN": random_string(),
    "X-ADVERTISER-ID": random_string(),
    "X-AJAX-REAL-METHOD": random_string(),
    "X_ALTO_AJAX_KEY": random_string(),
    "X-ALTO-AJAX-KEYZ": random_string(),
    "X-AMZ-DATE": "Mon, 10 Mar 2025 12:00:00 GMT",
    "X-AMZN-REMAPPED-HOST": ip,
    "X-AMZ-WEBSITE-REDIRECT-LOCATION": random_string(),
    "X-API-KEY": random_string(),
    "X-API-SIGNATURE": random_string(),
    "X-API-TIMESTAMP": random_string(),
    "X-APITOKEN": random_string(),
    "X-APPLE-CLIENT-APPLICATION": random_string(),
    "X-APPLE-STORE-FRONT": random_string(),
    "X-ARR-LOG-ID": random_string(),
    "X-ARR-SSL": random_string(),
    "X-ATT-DEVICEID": random_string(),
    "X-AUTHENTICATION": f"Bearer {generate_random_jwt()}",
    "X-AUTHENTICATION-KEY": f"Bearer {generate_random_jwt()}",
    "X-AUTH-KEY": f"Bearer {generate_random_jwt()}",
    "X-AUTH-MODE": f"Bearer {generate_random_jwt()}",
    "X-AUTHORIZATION": f"Bearer {generate_random_jwt()}",
    "XAUTHORIZATION": f"Bearer {generate_random_jwt()}",
    "X-AUTH-PASSWORD": f"Bearer {generate_random_jwt()}",
    "X-AUTH-SERVICE-PROVIDER": f"Bearer {generate_random_jwt()}",
    "X-AUTH-TOKEN": f"Bearer {generate_random_jwt()}",
    "X-AUTH-USER": f"Bearer {generate_random_jwt()}",
    "X-AUTH-USERID": f"Bearer {generate_random_jwt()}",
    "X-AUTH-USERNAME": f"Bearer {generate_random_jwt()}",
    "X-AVANTGO-SCREENSIZE": random_string(),
    "X-AZC-REMOTE-ADDR": ip,
    "X-BEAR-AJAX-REQUEST": random_string(),
    "X-BLUECOAT-VIA": "1.1 proxy",
    "X-BOLT-PHONE-UA": random_string(),
    "X-BROWSER-HEIGHT": random_string(),
    "X-BROWSER-WIDTH": random_string(),
    "X-CASCADE": random_string(),
    "X-CEPT-ENCODING": "gzip, deflate",
    "X-CF-URL": "https://" + ip,
    "X-CHROME-EXTENSION": random_string(),
    "X-CISCO-BBSM-CLIENTIP": ip,
    "X-CLIENT-HOST": ip,
    "X-CLIENT-ID": random_string(),
    "X-CLIENT-IP": ip,
    "X-CLIENTIP": ip,
    "X-CLIENT-KEY": random_string(),
    "X-CLIENT-OS": random_string(),
    "X-CLIENT-OS-VER": random_string(),
    "X-CLUSTER-CLIENT-IP": ip,
    "X-CODECEPTION-CODECOVERAGE": random_string(),
    "X-CODECEPTION-CODECOVERAGE-CONFIG": random_string(),
    "X-CODECEPTION-CODECOVERAGE-DEBUG": random_string(),
    "X-CODECEPTION-CODECOVERAGE-SUITE": random_string(),
    "X-COLLECT-COVERAGE": random_string(),
    "X-COMING-FROM": random_string(),
    "X-CONFIRM-DELETE": random_string(),
    "X-CONTENT-TYPE": "application/json",
    "X-CONTENT-TYPE-OPTIONS": "application/json",
    "X-CREDENTIALS-REQUEST": random_string(),
    "X-CSRF-CRUMB": random_string(),
    "X-CSRF-TOKEN": random_string(),
    "X-CSRFTOKEN": random_string(),
    "X-CUID": random_string(),
    "X-CUSTOM": random_string(),
    "X-DAGD-PROXY": ip,
    "X-DAVICAL-TESTCASE": random_string(),
    "X-DCMGUID": random_string(),
    "X-DEBUG-TEST": random_string(),
    "X-DEVICE-USER-AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "X-DIALOG": random_string(),
    "X-DNS-PREFETCH-CONTROL": random_string(),
    "X-DOKUWIKI-DO": random_string(),
    "X-DO-NOT-TRACK": random_string(),
    "X-DRESTCG": random_string(),
    "X-DSID": random_string(),
    "X-ELGG-APIKEY": random_string(),
    "X-ELGG-HMAC": random_string(),
    "X-ELGG-HMAC-ALGO": random_string(),
    "X-ELGG-NONCE": random_string(),
    "X-ELGG-POSTHASH": random_string(),
    "X-ELGG-POSTHASH-ALGO": random_string(),
    "X-ELGG-TIME": random_string(),
    "X-EM-UID": random_string(),
    "X-ENABLE-COVERAGE": random_string(),
    "X-ENVIRONMENT-OVERRIDE": random_string(),
    "X-EXPECTED-ENTITY-LENGTH": random_string(),
    "X-EXPERIENCE-API-VERSION": random_string(),
    "X-FB-USER-REMOTE-ADDR": ip,
    "X-FILE-ID": random_string(),
    "X-FILE-NAME": random_string(),
    "X-FILENAME": random_string(),
    "X-FILE-RESUME": random_string(),
    "X-FILE-SIZE": random_string(),
    "X-FILE-TYPE": random_string(),
    "X-FIRELOGGER": random_string(),
    "X-FIRELOGGERAUTH": f"Bearer {generate_random_jwt()}",
    "X-FIREPHP-VERSION": random_string(),
    "X-FLASH-VERSION": random_string(),
    "X-FLX-CONSUMER-KEY": random_string(),
    "X-FLX-CONSUMER-SECRET": random_string(),
    "X-FLX-REDIRECT-URL": "https://" + ip,
    "X-FOO": random_string(),
    "X-FOO-BAR": random_string(),
    "X-FORWARDED": random_string(),
    "X-FORWARDED-BY": random_string(),
    "X-FORWARDED-FOR": random_string(),
    "X-FORWARDED-FOR-ORIGINAL": "https://" + ip,
    "X-FORWARDED-HOST": ip,
    "X-FORWARDED-PORT": random_string(),
    "X-FORWARDED-PROTO": random_string(),
    "X-FORWARDED-PROTOCOL": random_string(),
    "X-FORWARDED-SCHEME": random_string(),
    "X-FORWARDED-SERVER": "nginx",
    "X-FORWARDED-SSL": random_string(),
    "X-FORWARDER-FOR": random_string(),
    "X-FORWARD-FOR": random_string(),
    "X-FORWARD-PROTO": random_string(),
    "X-FROM": random_string(),
    "X-GB-SHARED-SECRET": random_string(),
    "X-GEOIP-COUNTRY": ip,
    "X-GET-CHECKSUM": random_string(),
    "X-HELPSCOUT-EVENT": random_string(),
    "X-HELPSCOUT-SIGNATURE": random_string(),
    "X-HGARG-": random_string(),
    "X-HOST": ip,
    "X-HTTP-DESTINATIONURL": "https://" + ip,
    "X-HTTP-HOST-OVERRIDE": ip,
    "X-HTTP-METHOD": random_string(),
    "X-HTTP-METHOD-OVERRIDE": random_string(),
    "X-HTTP-PATH-OVERRIDE": random_string(),
    "X-HTTPS": random_string(),
    "X-HTX-AGENT": random_string(),
    "X-HUAWEI-USERID": random_string(),
    "X-HUB-SIGNATURE": random_string(),
    "X-IF-UNMODIFIED-SINCE": random_string(),
    "X-IMBO-TEST-CONFIG": random_string(),
    "X-INSIGHT": random_string(),
    "X-IP": ip,
    "X-IP-TRAIL": ip,
    "X-IWPROXY-NESTING": ip,
    "X-JPHONE-COLOR": random_string(),
    "X-JPHONE-DISPLAY": random_string(),
    "X-JPHONE-GEOCODE": random_string(),
    "X-JPHONE-MSNAME": random_string(),
    "X-JPHONE-UID": random_string(),
    "X-JSON": random_string(),
    "X-KALTURA-REMOTE-ADDR": ip,
    "X-KNOWN-SIGNATURE": random_string(),
    "X-KNOWN-USERNAME": random_string(),
    "X-LITMUS": random_string(),
    "X-LITMUS-SECOND": random_string(),
    "X-LOCKING": random_string(),
    "X-MACHINE": random_string(),
    "X-MANDRILL-SIGNATURE": random_string(),
    "X-METHOD-OVERRIDE": random_string(),
    "X-MOBILE-GATEWAY": random_string(),
    "X-MOBILE-UA": random_string(),
    "X-MOSSO-DT": random_string(),
    "X-MOZ": random_string(),
    "X-MSISDN": random_string(),
    "X-MS-POLICYKEY": random_string(),
    "X-MYQEE-SYSTEM-DEBUG": random_string(),
    "X-MYQEE-SYSTEM-HASH": random_string(),
    "X-MYQEE-SYSTEM-ISADMIN": random_string(),
    "X-MYQEE-SYSTEM-ISREST": random_string(),
    "X-MYQEE-SYSTEM-PATHINFO": random_string(),
    "X-MYQEE-SYSTEM-PROJECT": random_string(),
    "X-MYQEE-SYSTEM-RSTR": random_string(),
    "X-MYQEE-SYSTEM-TIME": random_string(),
    "X-NETWORK-INFO": random_string(),
    "X-NFSN-HTTPS": random_string(),
    "X-NING-REQUEST-URI": random_string(),
    "X-NOKIA-BEARER": random_string(),
    "X-NOKIA-CONNECTION-MODE": "keep-alive",
    "X-NOKIA-GATEWAY-ID": random_string(),
    "X-NOKIA-IPADDRESS": ip,
    "X-NOKIA-MSISDN": random_string(),
    "X-NOKIA-WIA-ACCEPT-ORIGINAL": "https://" + ip,
    "X-NOKIA-WTLS": random_string(),
    "X-NUGET-APIKEY": random_string(),
    "X-OC-MTIME": random_string(),
    "XONNECTION": random_string(),
    "X-OPERA-INFO": random_string(),
    "X-OPERAMINI-FEATURES": random_string(),
    "X-OPERAMINI-PHONE": random_string(),
    "X-OPERAMINI-PHONE-UA": random_string(),
    "X-OPTIONS": random_string(),
    "X-ORANGE-ID": "bytes=0-1024",
    "X-ORCHESTRA-SCHEME": random_string(),
    "X-ORIG-CLIENT": random_string(),
    "X-ORIGINAL-HOST": ip,
    "X-ORIGINAL-HTTP-COMMAND": "https://" + ip,
    "X-ORIGINALLY-FORWARDED-FOR": "https://" + ip,
    "X-ORIGINALLY-FORWARDED-PROTO": "https://" + ip,
    "X-ORIGINAL-REMOTE-ADDR": ip,
    "X-ORIGINAL-URL": "https://" + ip,
    "X-ORIGINAL-USER-AGENT": "https://" + ip,
    "X-ORIGINATING-IP": ip,
    "X-OS-PREFS": random_string(),
    "X-OVERLAY": random_string(),
    "X-PAGELET-FRAGMENT": random_string(),
    "X-PASSWORD": random_string(),
    "XPDB-DEBUGGER": random_string(),
    "X-PHABRICATOR-CSRF": random_string(),
    "X-PHPBB-USING-PLUPLOAD": random_string(),
    "X-PJAX": random_string(),
    "X-PJAX-CONTAINER": random_string(),
    "X-PROTOTYPE-VERSION": random_string(),
    "XPROXY": ip,
    "X-PROXY-URL": "https://" + ip,
    "X-PSWD": random_string(),
    "X-PURPOSE": random_string(),
    "X-QAFOO-PROFILER": random_string(),
    "X-REAL-IP": ip,
    "X-REMOTE-ADDR": ip,
    "X-REMOTE-PROTOCOL": random_string(),
    "X-RENDER-PARTIAL": random_string(),
    "X-REQUEST": random_string(),
    "X-REQUESTED-WITH": random_string(),
    "X-REQUEST-ID": random_string(),
    "X-REQUEST-SIGNATURE": random_string(),
    "X-REQUEST-START": random_string(),
    "X-REQUEST-TIMESTAMP": random_string(),
    "X-RESPONSE-FORMAT": random_string(),
    "X-REST-CORS": random_string(),
    "X-REST-PASSWORD": random_string(),
    "X-REST-USERNAME": random_string(),
    "X-REWRITE-URL": "https://" + ip,
    "XROXY-CONNECTION": "keep-alive",
    "X-SAKURA-FORWARDED-FOR": random_string(),
    "X-SCALR-AUTH-KEY": f"Bearer {generate_random_jwt()}",
    "X-SCALR-AUTH-TOKEN": f"Bearer {generate_random_jwt()}",
    "X-SCALR-ENV-ID": random_string(),
    "X-SCANNER": random_string(),
    "X-SCHEME": random_string(),
    "X-SCREEN-HEIGHT": random_string(),
    "X-SCREEN-WIDTH": random_string(),
    "X-SENDFILE-TYPE": random_string(),
    "X-SERIALIZE": random_string(),
    "X-SERIAL-NUMBER": random_string(),
    "X-SERVER-ID": "nginx",
    "X-SERVER-NAME": "nginx",
    "X-SERVER-PORT": "nginx",
    "X-SIGNATURE": random_string(),
    "X-SINA-PROXYUSER": ip,
    "X-SKYFIRE-PHONE": random_string(),
    "X-SKYFIRE-SCREEN": random_string(),
    "X-SSL": random_string(),
    "X-SUBDOMAIN": random_string(),
    "X-TE": random_string(),
    "X-TEAMSITE-PREREMAP": random_string(),
    "X-TEST-SESSION-ID": random_string(),
    "X-TIMER": random_string(),
    "X-TINE20-JSONKEY": random_string(),
    "X-TINE20-REQUEST-TYPE": random_string(),
    "X-TOMBOY-CLIENT": random_string(),
    "X-TOR": random_string(),
    "X-TWILIO-SIGNATURE": random_string(),
    "X-UA-DEVICE": random_string(),
    "X-UCBROWSER-DEVICE-UA": random_string(),
    "X-UIDH": random_string(),
    "X-UNIQUE-ID": random_string(),
    "X-UNIQUEWCID": random_string(),
    "X-UP-CALLING-LINE-ID": random_string(),
    "X-UPDATE": "Mon, 10 Mar 2025 12:00:00 GMT",
    "X-UPDATE-RANGE": "Mon, 10 Mar 2025 12:00:00 GMT",
    "X-UP-DEVCAP-ISCOLOR": random_string(),
    "X-UP-DEVCAP-SCREENDEPTH": random_string(),
    "X-UP-DEVCAP-SCREENPIXELS": random_string(),
    "X-UPLOAD-MAXRESOLUTION": random_string(),
    "X-UPLOAD-NAME": random_string(),
    "X-UPLOAD-SIZE": random_string(),
    "X-UPLOAD-TYPE": random_string(),
    "X-UP-SUBNO": random_string(),
    "X-URL-SCHEME": "https://" + ip,
    "X-USER": random_string(),
    "X-USER-AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "X-USERNAME": random_string(),
    "X-VARNISH": random_string(),
    "X-VERIFY-CREDENTIALS-AUTHORIZATION": f"Bearer {generate_random_jwt()}",
    "X-VODAFONE-3GPDPCONTEXT": random_string(),
    "X-WAP-CLIENTID": random_string(),
    "X-WAP-CLIENT-SDU-SIZE": random_string(),
    "X-WAP-GATEWAY": random_string(),
    "X-WAP-NETWORK-CLIENT-IP": ip,
    "X-WAP-NETWORK-CLIENT-MSISDN": random_string(),
    "X-WAP-PROFILE": random_string(),
    "X-WAP-PROXY-COOKIE": "sessionid=xyz123",
    "X-WAP-SESSION-ID": random_string(),
    "X-WAP-TOD": random_string(),
    "X-WAP-TOD-CODED": random_string(),
    "X-WHATEVER": random_string(),
    "X-WIKIMEDIA-DEBUG": random_string(),
    "X-WP-NONCE": random_string(),
    "X-WP-PJAX-PREFETCH": random_string(),
    "X-WS-API-KEY": random_string(),
    "X-XC-SCHEMA-VERSION": random_string(),
    "X-XHPROF-DEBUG": random_string(),
    "X-XHR-REFERER": "https://" + ip,
    "X-XMLHTTPREQUEST": random_string(),
    "X-XPID": random_string(),
    "XXX-REAL-IP": ip,
    "XXXXXXXXXXXXXXX": random_string(),
    "X-ZIKULA-AJAX-TOKEN": random_string(),
    "X-ZOTERO-VERSION": random_string(),
    "X-ZTGO-BEARERINFO": random_string(),
    "Y": random_string(),
    "ZOTERO-API-VERSION": random_string(),
    "ZOTERO-WRITE-TOKEN": random_string()
    } 
    return headers

user_agents = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0",
    "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko",
    "Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0",
    "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
    "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0",
]


def random_string(length = random.randint(5, 20)):
    chars = string.ascii_letters + string.digits + string.punctuation
    return ''.join(random.choice(chars) for _ in range(length))

def generate_random_jwt():
    payload = {
        "sub": random_string(10),
        "iat": int(time.time()),
        "exp": int(time.time()) + random.randint(3600, 86400),  # Expires in 1-24 hours
        "user": random_string(8)
    }
    secret = random_string(32)
    return jwt.encode(payload, secret, algorithm="HS256")

def make_request(url, headers, method):
    try:
        resp = requests.request(method, url, headers=headers, timeout=8, verify=False)
        return resp, resp.content.decode(errors='ignore')
    except Exception as e:
        print(Fore.RED + f"[!] Error: {e}")
        return None, None

def log_to_file(result):
    with open('XResults.json', 'a') as log_file:
        json.dump(result, log_file, indent=4)
        log_file.write('\n')

def repeater(url, header, value, method):
    time.sleep(random.uniform(0.3, 0.8))  # Reduce delay for faster execution
    
    initial_resp, init_content = make_request(url, {}, method)
    if not initial_resp:
        return
    
    initial_hash = hashlib.sha256(init_content.encode('utf-8')).hexdigest()
    
    # Second request (checks natural content variability)
    second_resp, second_content = make_request(url, {}, method)
    if not second_resp:
        return
    
    dynamic_content = initial_hash != hashlib.sha256(second_content.encode('utf-8')).hexdigest()
    
    # Third request (with injected header)
    headers = {header: value}
    modified_resp, modified_content = make_request(url, headers, method)
    if not modified_resp:
        return
    
    modified_hash = hashlib.sha256(modified_content.encode('utf-8')).hexdigest()
    
    # Change detection
    status_changed = modified_resp.status_code != initial_resp.status_code
    hash_diff = modified_hash != initial_hash if not dynamic_content else False
    
    # Reflection Detection
    reflection = False
    reflections = {"headers": [], "content": False}

    for resp_header, header_value in modified_resp.headers.items():
        if value in header_value:
            reflection = True
            reflections['headers'].append(resp_header)
    
    if value in modified_content:
        reflections['content'] = True
        reflection = True
    
    # Prepare the result for logging
    result = {
        "target": url,
        "header": header,
        "value": value,
        "status_code": modified_resp.status_code,
        "content_sha256": modified_hash,
        "reflection_detected": reflection,
        "reflection_details": reflections,
        "status_changed": status_changed,
        "hash_diff": hash_diff,
        "initial_request": {
            "status_code": initial_resp.status_code,
            "content_sha256": initial_hash,
            "initial_content": init_content[:200]  #
        }
    }
    
    # Print only if a change is detected
    if status_changed or hash_diff:
        color = Fore.GREEN if 200 <= modified_resp.status_code < 300 else Fore.YELLOW if modified_resp.status_code in [401, 403] else Fore.BLUE
        print(Fore.GREEN + '{ Alhamdulellah }', Fore.CYAN + '[ Resp Changed ]',
              Fore.RESET + 'Target:', Fore.MAGENTA + url,
              "Header:", Fore.MAGENTA + f"{header}: {value}",
              "StatusCode:", color, modified_resp.status_code,
              Fore.BLUE + "Content SHA256:", Fore.RESET, modified_hash)

        if reflection:
            msg = "Headers: " + str(reflections['headers']) if reflections['headers'] else ""
            msg += " Check Content" if reflections['content'] else ""
            print(Fore.GREEN + '{ Alhamdulellah }', Fore.RED + "[ REFLECTION DETECTED ]", Fore.CYAN + f"{url} - ", Fore.RED + header, Fore.CYAN + msg)
        
        # Log the result to a JSON file
        log_to_file(result)
def scanner(url, method, ip_value, threads):
    headers = headers_organizer(ip_value)
    with ThreadPoolExecutor(max_workers=threads) as executor:
        for header, value in headers.items():
            executor.submit(repeater, url, header, value, method)

def main(args):
    method = args.method.upper()
    if 'http' in args.targets:
        urls = [args.targets]
    else:
        with open(args.targets, 'r') as f:
            urls = f.read().splitlines()
    
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        for url in urls:
            executor.submit(scanner, url, method, args.ip_value, args.workers)

if __name__ == '__main__':
    print(banner)
    print("🚀 HeadX - Optimized Header Scanner 🚀")
    parser = ArgumentParser(description="HeadX advanced Header enumerator by @ace7ti")
    parser.add_argument('-t', '--targets', help='File containing targets or URL', required=True)
    parser.add_argument('-w', '--workers', help='Number of workers', default=10, type=int)
    parser.add_argument('-ip', '--ip-value', help='Specify a value for IP/URL related Headers { Useful for OOB Testing } (Optional)', required=False, default="127.0.0.1")
    parser.add_argument('-m', '--method', help='HTTP Request method (GET/POST/... )', default="GET")
    args = parser.parse_args()
    main(args)
